export const EventName = {
  OPEN_NETWORK: 'OPEN_NETWORK',
  CLOSE_NETWORK: 'CLOSE_NETWORK',
  CONNECT_PEER: 'CONNECT_PEER',
  DISCONNECT_PEER: 'DISCONNECT_PEER',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UPDATE_GAME_OBJECT: 'UPDATE_GAME_OBJECT'
} as const