export const EVENT_NAME = {
  OPEN_NETWORK: 'OPEN_NETWORK',
  CLOSE_NETWORK: 'CLOSE_NETWORK',
  CONNECT_PEER: 'CONNECT_PEER',
  DISCONNECT_PEER: 'DISCONNECT_PEER',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UPDATE_GAME_OBJECT: 'UPDATE_GAME_OBJECT',
  DELETE_GAME_OBJECT: 'DELETE_GAME_OBJECT',
  REQUEST_GAME_OBJECT: 'REQUEST_GAME_OBJECT',
  SYNCHRONIZE_GAME_OBJECT: 'SYNCHRONIZE_GAME_OBJECT',
  // ↑ ユドナリウム core
  SEND_SIMPLE_MESSAGE: 'SEND_SIMPLE_MESSAGE'
} as const

export type EventName = typeof EVENT_NAME[keyof typeof EVENT_NAME]